### ISSUE TITLE
Velocity Editor with no syntax coloring

### ISSUE THREAD

**Issue by hski-github** [vaulttec/veloedit#10]
I have installed Veloedit for Eclipse Mars.2 via Marketplace access from within Eclipse and clicked on install there. There was something installed e.g. a velocity editor was available, but when opening a vm file with this velocity editor, there was no coloring in the editor. I then tried to install via Update site and choosed Velocity UI (some maven plugin was depending to be updated). But again Velocity Editor does not show syntax coloring.

**Comment by lazarkovacevic** [comment]
The same problem in Mars.2, Neon and Neon.1.

**Comment by glewe** [comment]
Same here with Neon! Fix appreciated.

**Comment by glewe** [comment]
Using Eclipse Neon and Install New Software pointing to 
https://raw.githubusercontent.com/vaulttec/veloedit/updatesite/

An update was performed. Now the syntax highlighting is totally gone.

Looking that the File Associations, the Velocity Editor is not available anymore.

**Comment by tjuerge** [comment]
@glewe
Starting with version 1.0.7 the [editor leverages](https://github.com/vaulttec/veloedit/blob/develop/org.vaulttec.velocity.core/plugin.xml#L4) the extension point [`org.eclipse.core.contenttype.contentTypes`](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_contenttype_contentTypes.html) instead of the old file associations mechanism:

![screenshot eclipse neon 1 veloedit 1 0 7](https://cloud.githubusercontent.com/assets/2626998/20458588/7c828360-aea9-11e6-9298-22a533a85307.png)

So add your custom file associations to the list of the Velocity editors content types now.

**Comment by glewe** [comment]
Thanks. That resolved it. My extension *.vtl was not in that list.
